### ISSUE TITLE
Meetup API xml 

### ISSUE THREAD

**Issue by bodaonline** [feedjira/feedjira#305]
Hi,

new to Rails so not sure what's going on here this might not be a bug or might be issue with Faraday:

I managed to set up Feedjira and RSS (not meetup) parsing works fine. Just to show that feedjira is setup well:
```
def self.update_from_feed(url)
       feed = Feedjira::Feed.fetch_and_parse url
        feed.entries.each do |entry|
         unless exists? :title => entry.title
          create!(
            :title        => entry.title,
            :description  => entry.summary,
            :url          => entry.url,
            :user_id      => "1"
           )
          end
        end
     end
```

This is what happens in console with meetup API request which seems OK, although it is not displayed in a way the RSS was like: @title=..., @date=... etc:
```
=> url = "https://api.meetup.com/2/events.xml?key=MYAPIKEYREPLACED&group_urlname=ny-tech&sign=true&only=id,name"
>> xml = Faraday.get(url).body
=> "<?xml version='1.0' encoding='utf-8'?>\n<results><head><next /><method>Events</method>
<total_count>5</total_count><link>https://api.meetup.com/2/events.xml</link><count>5</count>
<description>Access Meetup events using a group, member, or event id. Events in private groups are available
 only to authenticated members of those groups. To search events by topic or location, see 
[Open Events](/meetup_api/docs/2/open_events).</description>
<lon /><title>Meetup Events v2</title>
<url>https://api.meetup.com/2/events.xml?offset=0&amp;sign=True&amp;format=xml&amp;limited_events=False&amp;group_urlname=ny-tech&amp;only=id%2Cname&amp;page=200&amp;fields=&amp;key=MYAPIKEYREPLACED&amp;order=time&amp;desc=false&amp;status=upcoming</url>
<signed_url>https://api.meetup.com/2/events.xml?offset=0&amp;format=xml&amp;limited_events=False&amp;group_urlname=ny-tech&amp;only=id%2Cname&amp;page=200&amp;fields=&amp;order=time&amp;desc=false&amp;status=upcoming&amp;sig_id=13361107&amp;sig=326ef283305b4009b32066af40966bdb433ef0e0</signed_url><id /><updated>Fri Feb 05 12:51:19 EST 2016</updated><lat /></head>
<items><item><name>February 2016 NY Tech Meetup and Afterparty</name><id>226570627</id></item>
<item><name>March 2016 NY Tech Meetup and Afterparty</name><id>226570993</id></item>
<item><name>April 2016 NY Tech Meetup and Afterparty</name><id>227889462</id></item>
<item><name>May 2016 NY Tech Meetup and Afterparty</name><id>227889545</id></item>
<item><name>June 2016 NY Tech Meetup and Afterparty</name><id>227889626</id></item></items></results>\n"
```

But when I try to use my method from the model I get error:
Event.rb:
```
  def self.update_from_xml(url)
    xml = Faraday.get(url).body
    feed = Feedjira::Feed.fetch_and_parse xml
    feed.entries.each do |entry|
      unless exists? :title => entry.title
      create!(
          :title        => entry.name,
          :description  => entry.summary,
          :url          => entry.url,
          :user_id      => "1"
        )
      end
    end
  end
```

Console:
```
>> Event.update_from_xml("https://api.meetup.com/2/events.xml?key=MYAPIKEYREPLACED&group_urlname=ny-tech&sign=true&only=id,name")
URI::InvalidURIError: bad URI(is not URI?): <?xml version='1.0' encoding='utf-8'?>
<results><head><next /><method>Events</method><total_count>5</total_count>
<link>https://api.meetup.com/2/events.xml</link><count>5</count><description>
Access Meetup events using a group, member, or event id. Events in private groups 
are available only to authenticated members of those groups. To search events by topic 
or location, see [Open Events](/meetup_api/docs/2/open_events).</description><lon />
<title>Meetup Events v2</title><url>https://api.meetup.com/2/events.xml?offset=0&amp;sign=True&amp;format=xml&amp;limited_events=False&amp;group_urlname=
ny-tech&amp;only=id%2Cname&amp;page=200&amp;fields=&amp;key=MYAPIKEYREPLACED
&amp;order=time&amp;desc=false&amp;status=upcoming</url><signed_url>https://api.meetup.com/2/events.xml?offset=0&amp;format=xml&amp;limited_events=False&amp;group_urlname=ny-tech&amp;only=id%2Cname&amp;page=200&amp;fields=&amp;order=time&amp;desc=false
&amp;status=upcoming&amp;sig_id=13361107&amp;sig=326ef283305b4009b32066af40966bdb433ef0e0</signed_url><id /><updated>Fri Feb 05 12:51:19 EST 2016</updated><lat /></head>
<items><item><name>February 2016 NY Tech Meetup and Afterparty</name><id>226570627</id></item>
<item><name>March 2016 NY Tech Meetup and Afterparty</name><id>226570993</id></item>
<item><name>April 2016 NY Tech Meetup and Afterparty</name><id>227889462</id></item>
<item><name>May 2016 NY Tech Meetup and Afterparty</name><id>227889545</id></item>
<item><name>June 2016 NY Tech Meetup and Afterparty</name><id>227889626</id></item></items></results>

        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/uri/common.rb:176:in `split'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/uri/common.rb:1232:in `URI'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/faraday-0.9.2/lib/faraday/utils.rb:258:in `call'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/faraday-0.9.2/lib/faraday/utils.rb:258:in `URI'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/faraday-0.9.2/lib/faraday/connection.rb:309:in `url_prefix='
        from /usr/local/rvm/gems/ruby-2.1.4/gems/faraday-0.9.2/lib/faraday/connection.rb:77:in `initialize'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/faraday-0.9.2/lib/faraday.rb:70:in `new'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/faraday-0.9.2/lib/faraday.rb:70:in `new'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/feedjira-2.0.0/lib/feedjira/feed.rb:80:in `connection'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/feedjira-2.0.0/lib/feedjira/feed.rb:66:in `fetch_and_parse'
        from /home/ubuntu/workspace/prg/app/models/event.rb:24:in `update_from_xml'
        from (irb):22
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /home/ubuntu/workspace/prg/bin/rails:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

I also tried
url = "..."
xml = Faraday.get(url)
```
 #<Faraday::Response:0x007f4a192fc320 @on_complete_callbacks=[], @env=#
<Faraday::Env @method=:get @body="<?xml version='1.0' encoding='utf-8'?>\n<results>
<head><next /><method>Events</method><total_count>5</total_count><link>https://api.meetup.com/2/events.xml</link><count>5</count>
<description>Access Meetup events using a group, member, or event id. Events in 
private groups are available only to authenticated members of those groups. To search 
events by topic or location, see [Open Events](/meetup_api/docs/2/open_events).</description>
<lon /><title>Meetup Events v2</title><url>https://api.meetup.com/2/events.xml?offset=0&amp;sign=True&amp;format=xml&amp;limited_events=False&amp;group_urlname=ny-tech&amp;only=id%2Cname&amp;page=200&amp;fields=&amp;key=MYAPIKEY&amp;order=time&
amp;desc=false&amp;status=upcoming</url><signed_url>https://api.meetup.com/2/events.xml?offset=0&amp;format=xml&amp;limited_events=False&amp;group_urlname=ny-tech&amp;only=id%2Cname&amp;page=200&amp;fields=&amp;order=time&amp;desc=false&
amp;status=upcoming&amp;sig_id=13361107&amp;sig=326ef283305b4009b32066af40966bdb433ef0e0</signed_url><id />
<updated>Fri Feb 05 12:51:19 EST 2016</updated><lat /></head><items>
<item><name>February 2016 NY Tech Meetup and Afterparty</name><id>226570627</id></item>
<item><name>March 2016 NY Tech Meetup and Afterparty</name><id>226570993</id></item>
<item><name>April 2016 NY Tech Meetup and Afterparty</name><id>227889462</id></item>
<item><name>May 2016 NY Tech Meetup and Afterparty</name><id>227889545</id></item>
<item><name>June 2016 NY Tech Meetup and Afterparty</name><id>227889626</id></item></items></results>\n" @url=#<URI::HTTPS:0x007f4a192e5198 URL:https://api.meetup.com/2/events.xml?group_urlname=ny-tech&key=MYAPIKEY&only=id%2Cname&sign=true> 
@request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.9.2"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x007f4a192fc320 ...> 
@response_headers={"server"=>"cloudflare-nginx", "date"=>"Sat, 06 Feb 2016 09:54:47 GMT", "content-type"=>"application/xml;charset=utf-8", "content-length"=>"674", "connection"=>"close", "set-cookie"=>"__cfduid=dda3d65cc86c9ca56ab631ceabfff4eae1454752486; expires=Sun, 
05-Feb-17 09:54:46 GMT; path=/; domain=.meetup.com; HttpOnly", "x-meetup-server"=>"api16", 
"x-meetup-request-id"=>"47e5f38e-d2bc-4b90-90b5-0f0232991b0f", "x-ratelimit-limit"=>"30", 
"x-ratelimit-remaining"=>"29", "x-ratelimit-reset"=>"10", "x-oauth-scopes"=>"basic", 
"x-accepted-oauth-scopes"=>"basic", "etag"=>"\"254d434d38f6ad3bcb52cd3f56f03099\"", "vary"=>"Accept-Encoding,User-Agent", "cf-ray"=>"2705f9c147763bf3-CDG"} @status=200>>
```
feed = Feedjira::Feed.parse xml
Above gives me this error: NoMethodError: undefined method `slice' for #<Faraday::Response:0x007f4a192fc320>
...
...

So how could I make Feedjira parse meetup API responses? TIA!

**Comment by amatriain** [comment]
Feedjira is a gem for parsing RSS and Atom feeds. That URL you posted returns an XML response which seems to be a meetup-only format, it does not follow either the RSS nor Atom schemas.

The events method of the meetup API v2 does not seem to be able to return either RSS nor Atom responses, according to their docs. There is an activity method in v1 which seemingly can return RSS or Atom, maybe that's what you're looking for.

If you can get a valid Atom or RSS response from meetup, you should be able to parse it with Feedjira. Otherwise you'll have to write your own parser for their XML response format, Feedjira cannot help you there.

**Comment by bodaonline** [comment]
Thanks for the quick reply @amatriain , it looks like v1 events is deprecated. How much work would it be for somene knowledgeable? If you could do it for a fee pls email <myusername> at gmail. thx!

**Comment by jonallured** [comment]
Hi @bodaonline, I'm going to close this one - let us know if you need anything else on this.

Thanks!
Jon
